site_name: Playbook
site_description: 'Magrathea Labs Playbook'
repo_name: 'magrathealabs/playbook'
repo_url: 'https://github.com/magrathealabs/playbook'
pages:
  - "Introduction": index.md
  - "1. Organization": 1-organization.md
  - "1.1. Sharing": 1.1-sharing.md
  - "1.2. Communication": 1.2-communication.md
  - "1.3. Working": 1.3-working.md
  - "2. Projects": 2-projects.md
  - "2.1. Starting a new project": 2.1-new-projects.md
  - "3. Engineering": 3-engineering.md
  - "3.1. Guides": 3.1-Guides.md
  - "3.2. Environment Setup": 3.2-environment.md
  - "4. Operations": 4-Operations.md
  - "5. Talents": 5-Talents.md
  - "6. Code of Conduct": 6-code-of-conduct.md
  - "References": x-references.md
theme:
  name: material
  custom_dir: custom_theme
extra:
  palette:
  font:
    text: 'Open Sans'
    code: 'Ubuntu Mono'
  social:
    - type: 'github'
      link: 'https://github.com/magrathealabs'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/10337473'
    - type: 'facebook'
      link: 'https://www.facebook.com/magrathealabs'
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
